---
- name: Get provision user credentials
  ansible.builtin.import_role:
    name: provision
    tasks_from: credentials

- name: Run initial raspberry pi configuration as provision user
  vars:
    ansible_user: "{{ provision_user_username }}"
    ansible_ssh_pass: "{{ provision_user_password }}"
    ansible_become_pass: "{{ provision_user_password }}"
  ansible.builtin.import_tasks: initialise.yml
